const images: Record<string, any> = {
  "../assets/images/collaboratos-logos/eltropico-logo.jpg": require("../assets/images/collaboratos-logos/eltropico-logo.jpg"),
  "../assets/images/collaboratos-logos/frikibar-logo.jpg": require("../assets/images/collaboratos-logos/frikibar-logo.jpg"),
  "../assets/images/collaboratos-logos/oakberry-logo.jpeg": require("../assets/images/collaboratos-logos/oakberry-logo.jpeg"),
  "../assets/images/collaboratos-logos/clubdeportivofranco-logo.png": require("../assets/images/collaboratos-logos/clubdeportivofranco-logo.png"),
  "../assets/images/collaboratos-logos/alohaaclub-logo.jpeg": require("../assets/images/collaboratos-logos/alohaaclub-logo.jpeg"),
  "../assets/images/collaboratos-logos/autosansu-logo.png": require("../assets/images/collaboratos-logos/autosansu-logo.png"),
  "../assets/images/collaboratos-logos/mc-logo.jpg": require("../assets/images/collaboratos-logos/mc-logo.jpg"),
  "../assets/images/collaboratos-logos/crucesurfshop-logo.jpg": require("../assets/images/collaboratos-logos/crucesurfshop-logo.jpg"),
  "../assets/images/collaboratos-logos/palabras-logo.png": require("../assets/images/collaboratos-logos/palabras-logo.png"),
  "../assets/images/collaboratos-logos/junglehouse-logo.jpeg": require("../assets/images/collaboratos-logos/junglehouse-logo.jpeg"),
  "../assets/images/collaboratos-logos/dassie-logo.png": require("../assets/images/collaboratos-logos/dassie-logo.png"),
  "../assets/images/collaboratos-logos/quebueno-logo.png": require("../assets/images/collaboratos-logos/quebueno-logo.png"),
  "../assets/images/collaboratos-logos/masculzone-logo.png": require("../assets/images/collaboratos-logos/masculzone-logo.png"),
  "../assets/images/collaboratos-logos/tirma-logo.jpg": require("../assets/images/collaboratos-logos/tirma-logo.jpg"),
  "../assets/images/collaboratos-logos/3rjsurfschool-logo.png": require("../assets/images/collaboratos-logos/3rjsurfschool-logo.png"),
  "../assets/images/collaboratos-logos/thecouple-logo.png": require("../assets/images/collaboratos-logos/thecouple-logo.png"),
  "../assets/images/collaboratos-logos/alboroto-logo.png": require("../assets/images/collaboratos-logos/alboroto-logo.png"),
  "../assets/images/collaboratos-logos/fresquito-logo.png": require("../assets/images/collaboratos-logos/fresquito-logo.png"),
  "../assets/images/collaboratos-logos/lacan-logo.png": require("../assets/images/collaboratos-logos/lacan-logo.png"),
  "../assets/images/collaboratos-logos/ajilimonycanela-logo.jpg": require("../assets/images/collaboratos-logos/ajilimonycanela-logo.jpg"),
  "../assets/images/collaboratos-logos/luwak-logo.png": require("../assets/images/collaboratos-logos/luwak-logo.png"),
  "../assets/images/collaboratos-logos/gofit-logo.jpg": require("../assets/images/collaboratos-logos/gofit-logo.jpg"),
};

export default images;
